language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - python setup.py develop
  - python setup.py build_cannonsim
  - pip install pytest-cov
  - pip install coveralls
script:
  - py.test --pep8 easyvvuq/
  - py.test --cov=easyvvuq/ --pep8 tests --ignore=tests/test_vector.py --ignore=tests/test_integration.py --ignore=tests/test_worker.py --ignore=tests/test_multisampler.py
after_success:
  - coveralls
